- name: "1.1.1.1 | Ensure cramfs kernel module is not available (Automated)"
  block:

    - name: Check if cramfs kernel module is available
      command: modinfo cramfs
      register: cramfs_module
      ignore_errors: true
      changed_when: false

    - name: Unload cramfs kernel module if loaded
      ansible.builtin.shell: "modprobe -r cramfs"
      when: "'cramfs_module' in vars and cramfs_module.rc == 0"
      ignore_errors: true

    - name: Blacklist cramfs module
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/cramfs.conf
        line: "blacklist cramfs"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: "'cramfs_module' in vars and cramfs_module.rc == 0"

    - name: Prevent cramfs module from loading
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/cramfs.conf
        line: "install cramfs /bin/false"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: "'cramfs_module' in vars and cramfs_module.rc == 0"

  rescue:
    - name: Fallback info if cramfs_module was not defined
      debug:
        msg: "cramfs module not available or 'modinfo' command failed — skipping tasks"

- name: "1.1.1.2 | Ensure freevxfs kernel module is not available (Automated)"
  block:

    - name: Check if freevxfs kernel module is available
      command: modinfo freevxfs
      register: freevxfs_module
      ignore_errors: true
      changed_when: false

    - name: Unload freevxfs kernel module if loaded
      ansible.builtin.shell: "modprobe -r freevxfs"
      when: "'freevxfs_module' in vars and freevxfs_module.rc == 0"
      ignore_errors: true

    - name: Blacklist freevxfs module
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/freevxfs.conf
        line: "blacklist freevxfs"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: "'freevxfs_module' in vars and freevxfs_module.rc == 0"

    - name: Prevent freevxfs module from loading
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/freevxfs.conf
        line: "install freevxfs /bin/false"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: "'freevxfs_module' in vars and freevxfs_module.rc == 0"

  rescue:
    - name: Fallback info if freevxfs_module was not defined
      debug:
        msg: "freevxfs module not available or 'modinfo' command failed — skipping tasks"

# 1.1.1.3 Ensure hfs kernel module is not available
- name: Check if hfs kernel module is available
  command: modinfo hfs
  register: hfs_module
  ignore_errors: true
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.3

- name: Unload hfs kernel module if loaded
  command: modprobe -r hfs
  when: hfs_module.rc == 0
  ignore_errors: true
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.3

- name: Blacklist hfs module
  lineinfile:
    path: /etc/modprobe.d/hfs.conf
    line: "blacklist hfs"
    create: yes
  when: hfs_module.rc == 0
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.3

- name: Prevent hfs module from loading
  lineinfile:
    path: /etc/modprobe.d/hfs.conf
    line: "install hfs /bin/false"
    create: yes
  when: hfs_module.rc == 0
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.3

# 1.1.1.4 Ensure hfsplus kernel module is not available
- name: Check if hfsplus kernel module is available
  command: modinfo hfsplus
  register: hfsplus_module
  ignore_errors: true
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.4

- name: Unload hfsplus kernel module if loaded
  command: modprobe -r hfsplus
  when: hfsplus_module.rc == 0
  ignore_errors: true
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.4

- name: Blacklist hfsplus module
  lineinfile:
    path: /etc/modprobe.d/hfsplus.conf
    line: "blacklist hfsplus"
    create: yes
  when: hfsplus_module.rc == 0
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.4

- name: Prevent hfsplus module from loading
  lineinfile:
    path: /etc/modprobe.d/hfsplus.conf
    line: "install hfsplus /bin/false"
    create: yes
  when: hfsplus_module.rc == 0
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.4

# 1.1.1.5 Ensure jffs2 kernel module is not available
- name: Check if jffs2 kernel module is available
  command: modinfo jffs2
  register: jffs2_module
  ignore_errors: true
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.5

- name: Unload jffs2 kernel module if loaded
  command: modprobe -r jffs2
  when: jffs2_module.rc == 0
  ignore_errors: true
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.5

- name: Blacklist jffs2 module
  lineinfile:
    path: /etc/modprobe.d/jffs2.conf
    line: "blacklist jffs2"
    create: yes
  when: jffs2_module.rc == 0
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.5

- name: Prevent jffs2 module from loading
  lineinfile:
    path: /etc/modprobe.d/jffs2.conf
    line: "install jffs2 /bin/false"
    create: yes
  when: jffs2_module.rc == 0
  tags:
    - level1
    - server
    - workstation
    - cis_1.1.1.5

# 1.1.1.6 Ensure squashfs kernel module is not available
- name: Check if squashfs kernel module is available
  command: modinfo squashfs
  register: squashfs_module
  ignore_errors: true
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.6

- name: Unload squashfs kernel module if loaded
  command: modprobe -r squashfs
  when: squashfs_module.rc == 0
  ignore_errors: true
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.6

- name: Blacklist squashfs module
  lineinfile:
    path: /etc/modprobe.d/squashfs.conf
    line: "blacklist squashfs"
    create: yes
  when: squashfs_module.rc == 0
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.6

- name: Prevent squashfs module from loading
  lineinfile:
    path: /etc/modprobe.d/squashfs.conf
    line: "install squashfs /bin/false"
    create: yes
  when: squashfs_module.rc == 0
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.6

# 1.1.1.7 Ensure udf kernel module is not available
- name: Check if udf kernel module is available
  command: modinfo udf
  register: udf_module
  ignore_errors: true
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.7

- name: Unload udf kernel module if loaded
  command: modprobe -r udf
  when: udf_module.rc == 0
  ignore_errors: true
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.7

- name: Blacklist udf module
  lineinfile:
    path: /etc/modprobe.d/udf.conf
    line: "blacklist udf"
    create: yes
  when: udf_module.rc == 0
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.7

- name: Prevent udf module from loading
  lineinfile:
    path: /etc/modprobe.d/udf.conf
    line: "install udf /bin/false"
    create: yes
  when: udf_module.rc == 0
  tags:
    - level2
    - server
    - workstation
    - cis_1.1.1.7

# 1.1.1.8 Ensure usb-storage kernel module is not available
- name: Check if usb-storage kernel module is available
  command: modinfo usb-storage
  register: usb_storage_module
  ignore_errors: true
  tags:
    - level1
    - level2
    - server
    - workstation
    - cis_1.1.1.8

- name: Unload usb-storage kernel module if loaded
  command: modprobe -r usb-storage
  when: usb_storage_module.rc == 0
  ignore_errors: true
  tags:
    - level1
    - level2
    - server
    - workstation
    - cis_1.1.1.8

- name: Blacklist usb-storage kernel module
  lineinfile:
    path: /etc/modprobe.d/usb-storage.conf
    line: "blacklist usb-storage"
    create: yes
  when: usb_storage_module.rc == 0
  tags:
    - level1
    - level2
    - server
    - workstation
    - cis_1.1.1.8

- name: Prevent usb-storage kernel module from loading
  lineinfile:
    path: /etc/modprobe.d/usb-storage.conf
    line: "install usb-storage /bin/false"
    create: yes
  when: usb_storage_module.rc == 0
  tags:
    - level1
    - level2
    - server
    - workstation
    - cis_1.1.1.8

# 1.1.2.1.1 Ensure /tmp is a separate partition using tmpfs
- name: Ensure systemd tmp.mount is unmasked
  command: systemctl unmask tmp.mount
  ignore_errors: true
  tags:
    - cis_1.1.2.1.1

- name: Ensure /tmp mount directory exists
  file:
    path: /tmp
    state: directory
    mode: '1777'

- name: Add /tmp entry to /etc/fstab
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,rw,nosuid,nodev,noexec,relatime,size=2G
    state: mounted
  tags:
    - cis_1.1.2.1.1

- name: Ensure /tmp is mounted with nodev option
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,rw,nosuid,nodev,noexec,relatime,size=2G
    state: mounted
  tags:
    - cis_1.1.2.1.2

- name: Ensure /tmp is mounted with nosuid option
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,rw,nosuid,nodev,noexec,relatime,size=2G
    state: mounted
  tags:
    - cis_1.1.2.1.3

- name: Ensure /tmp is mounted with nodev, nosuid, and noexec
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,rw,nosuid,nodev,noexec,relatime,size=2G
    state: mounted
  tags:
    - cis_1.1.2.1.4


